global using CommonLib;
global using MessagePack;
global using Microsoft.Win32;
global using ScriptEditor.CustomControls;
global using System;
global using System.Collections.Generic;
global using System.ComponentModel;
global using System.IO;
global using System.Windows;
global using System.Windows.Controls;
global using System.Windows.Media;
global using static ScriptEditor.GlobalData;
